Asyncronously accessing the Discord API
Now that we have handling for the Discord
interactions and the responses going back
to Discord, we need to actually handle the
interaction and set the role on the user
that asked for it.

Next we need to actually set the role on
the given user and do the thing we've
been building up to. Which means we'll
need to make HTTP requests to the Discord
API. This is why when we set the permissions
for our interactions handler, we included bot.

To do that we'll add the `reqwest` package.

```shell
cargo add reqwest
```

It's likely that after installing `reqwest` you'll
run into this openssl-sys compile error the next
time you try to build the project.

```
error: failed to run custom build command for `openssl-sys v0.9.63`

Caused by:
  process didn't exit successfully: `/Users/chris/github/rust-adventure/_in-progress-netlify-discord-slash-commands/target/release/build/openssl-sys-4f575b806fe66f00/build-script-main` (exit code: 101)

<a lot more output>
```

This happens because we're cross-compiling
for the netlify functions environment. To fix
it we need to adjust the features that the
`reqwest` uses to compile.

Features are Rust's way of approaching conditional
compilation and optional dependencies. Features
allow you to place flags in your Rust codebase
that can be controlled from a Cargo.toml. These
flags, when turned on or off, control which pieces
of the codebase will compile.

Which brings us to what we need to do to `reqwest`:
diables the default-on features (including the native
openssl support), and enable an alternative implementation
using `rustls-tls`.

```toml
reqwest = { version = "0.11.3", features = ["rustls-tls"], default-features = false }
```

We'll set up a few constants that we'll use
later. First we'll get the Discord API base
URL with the appropriate [version](https://discord.com/developers/docs/reference#api-versioning-api-versions).

```rust
const DISCORD_API: &str = "https://discord.com/api/v9";
```

To identify our client application to discord
we specify a custom [user agent](https://discord.com/developers/docs/reference#user-agent) as well. We can take
advantage of the [`concat!` macro](https://doc.rust-lang.org/std/macro.concat.html)
to build our user agent up at compile time.

The second macro we're using here is the `env!`
macro, which will emit a compile error if the
environemnt variable we're looking for is not
defined. `CARGO_PKG_VERSION` is provided by
cargo when building, so we basically always
have it around, and the value is the value
of the version key in our `Cargo.toml`.

```rust
const USER_AGENT: &str = concat!(
	"DiscordBot (https://github.com/rust-adventure/netlify-discord-slash-commands, ",
	env!("CARGO_PKG_VERSION"),
	")"
);
```

We'll need to add a few fields to our `Interaction`
struct. We won't fill out all of the fields that
are available in the Discord docs, only some of
them, including the ones we'll need.

```rust
struct Interaction {
    #[serde(rename = "type")]
    interaction_type: InteractionType,
    data: Option<ApplicationCommandInteractionData>,
    guild_id: Option<Snowflake>,
    channel_id: Option<Snowflake>,
    member: Option<GuildMember>,
    token: String,
    version: usize,
}
pub struct GuildMember {
    pub deaf: bool,
    pub nick: Option<String>,
    pub roles: Vec<String>,
    /// Attached User struct.
    pub user: User,
}

pub struct User {
    pub id: Snowflake,
    pub avatar: Option<String>,
    pub bot: Option<bool>,
    pub discriminator: String,
    pub username: String,
}
```

After setting up the extra fields on our structs,
we can write the function that will handle setting
the role on the given user.

```rust
async fn set_role_for_user_in_guild<T: AsRef<str>>(
    role: T,
    user: &User,
    guild_id: Snowflake,
) -> InteractionResponse {
    let client = reqwest::Client::new();
    let res = client
        .put(&format!(
            "{}/guilds/{}/members/{}/roles/{}",
            DISCORD_API,
            guild_id,
            user.id,
            role.as_ref()
        ))
        .header("User-Agent", USER_AGENT)
        .header(
            "Authorization",
            format!("Bot {}", DISCORD_BOT_TOKEN.clone()),
        )
        .send()
        .await;

    match res {
        Err(e) => {
            error!(error = ?e);
            InteractionResponse::reply(format!(
                "failed to set role for {}",
                user.username
            ))
        }
        Ok(response) => {
            if response.status().is_success() {
                match ROLE_REVERSE_MAP.get(role.as_ref()) {
                    Some(name) => {
                        InteractionResponse::reply(format!(
                            "{} has accepted the {} role",
                            user.username, name
                        ))
                    }
                    None => {
                        InteractionResponse::reply(format!(
                            "{} has accepted a role",
                            user.username
                        ))
                    }
                }
            } else {
                InteractionResponse::reply(format!(
                    "Failed with status code {}",
                    response.status()
                ))
            }
        }
    }
}
```

The type signature of this function is set up
so that `role` can accept anything that can
turn into `&str`. That means `String`, `&String`,
`&str`, and more, which makes it nicer to use this
function.

We also take a shared reference to a `User`
because we only need to read values from it.

```rust
async fn set_role_for_user_in_guild<T: AsRef<str>>(
    role: T,
    user: &User,
    guild_id: Snowflake,
) -> InteractionResponse
```

Using the arguments we passed in and the
consts we defined, we can
construct the `PUT` request URL. Note the
use of `as_ref`, which is what the `AsRef`
trait gave us to work with.

We also need our `DISCORD_BOT_TOKEN`, which
we can take moment after writing this function
to set up.

```rust
let client = reqwest::Client::new();
let res = client
    .put(&format!(
        "{}/guilds/{}/members/{}/roles/{}",
        DISCORD_API,
        guild_id,
        user.id,
        role.as_ref()
    ))
    .header("User-Agent", USER_AGENT)
    .header(
        "Authorization",
        format!("Bot {}", DISCORD_BOT_TOKEN.clone()),
    )
    .send()
    .await;
```

`DISCORD_BOT_TOKEN` is an environment variable
that we'll get from the Netlify Functions
environment at runtime. To get this done, we'll
take advantage of `lazy_static` again.

```rust
static ref DISCORD_BOT_TOKEN: String = env::var("DISCORD_BOT_TOKEN")
```

While we're in `lazy_static` we can also set up
a `HashMap` that creates a relationship from
role id to name. We need this because Discord
doesn't hand us this information in the interaction
request. We could also make an http request to
Discord to get the full list of roles instead of
hard coding it here.

```rust
static ref ROLE_REVERSE_MAP: HashMap<&'static str, &'static str> = {
    let mut map = HashMap::new();
    map.insert("837304749312180285", "corgi");
    map
};
```

With the `set_role_for_user_in_guild` function
set up, we'll update the `role` command handling to
look like this.

```rust
"role" => {
    let maybe_user = &interaction.member.map(|member| member.user);
    let maybe_guild_id = interaction.guild_id;
    let maybe_role = options.and_then(|options| {
        options
            .iter()
            .find(|el| el.name == "i-want-to-be-a")
            .and_then(|v| v.value.clone())
    });
    match (maybe_user, maybe_guild_id, maybe_role) {
        (Some(user), Some(guild_id), Some(role)) => {
            let response = set_role_for_user_in_guild("", &user, guild_id).await;
            Ok(response.into_response())
        }
        (maybe_user, maybe_guild_id, maybe_role) => {
            error!(
                ?maybe_user,
                ?maybe_guild_id,
                ?maybe_role,
                "necessary information was not available"
            );
            Ok(
                InteractionResponse::reply("received role command".to_string())
                    .into_response(),
            )
        }
    }
}
```

We grab the arguments we'll need to pass to
our newly created function and match on them
as a single tuple so that we can match on all
of the values at once. If they are all `Some(value)`
then we can use them, if not something went
wrong.

Before deploying, make sure you've gone to
`https://discord.com/developers/applications/<app-id>/bot`
and set your `DISCORD_BOT_TOKEN` on netlify.